name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs bundle install and caches installed gems automatically
      
      # Install specific RubyGems version to avoid compatibility issues
      - name: Update RubyGems
        run: |
          gem update --system 3.3.22
          gem --version
      
      # Install dependencies
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      # Build the site
      - name: Build the site
        run: bundle exec jekyll build
        
      # Ensure notes_graph.json is in the _site directory
      - name: Copy notes_graph.json to _site
        run: |
          if [ -f "notes_graph.json" ]; then
            cp notes_graph.json _site/
          fi
          if [ -f "_includes/notes_graph.json" ]; then
            mkdir -p _site/_includes
            cp _includes/notes_graph.json _site/_includes/
          fi
          if [ -f "assets/js/notes_graph.json" ]; then
            mkdir -p _site/assets/js
            cp assets/js/notes_graph.json _site/assets/js/
          fi
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./_site
          publish_branch: gh-pages
